"""
Django settings for course_recommendation project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# BASE_DIR'i tanımla
BASE_DIR = Path(__file__).resolve().parent.parent

# Statik dosya ayarları
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # static klasörü için
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # staticfiles için

# Medya dosyaları (Eğer kullanıcıların dosya yüklemesini destekliyorsan)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Security settings
SECRET_KEY = 'django-insecure-5ca^216lxjco559^y^d*sr!6mx%87=-v^bz(83deawcl+f+^@a'

DEBUG = True

ALLOWED_HOSTS = []


# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'recommendations',  # Uygulamamız eklendi ✅
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'course_recommendation.urls'

# Templates configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Şablon klasörü tanımlandı ✅
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'course_recommendation.wsgi.application'


# Database configuration (PostgreSQL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'course_advice_db',
        'USER': 'course_user',
        'PASSWORD': '10701463',  # 🔐 Şifreyi buraya yaz
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',  # 🔥 Türkçe karakter desteği için eklendi ✅
        },
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'tr'  # 🔥 Türkçe dili için güncellendi ✅
TIME_ZONE = 'Europe/Istanbul'  # 🔥 Türkiye saat dilimi ✅
USE_I18N = True
USE_TZ = True

# Static files (CSS, JS, Images)
STATIC_URL = '/static/'  # Statik dosyalar için URL
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Uygulama içi statik dosyalar
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic için dizin ✅

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
