# Generated by Django 5.1.5 on 2025-02-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeslekiA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Mesleki A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeslekiB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Mesleki B', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SosyalSecmeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Sosyal Seçmeli', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniversiteMeslekiSecmeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Üniversite Mesleki Seçmeli', max_length=100)),
            ],
        ),
    ]
