# Generated by Django 5.1.5 on 2025-02-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meslekia',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meslekia',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meslekia',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meslekia',
            name='name',
        ),
        migrations.RemoveField(
            model_name='meslekib',
            name='category',
        ),
        migrations.RemoveField(
            model_name='meslekib',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meslekib',
            name='id',
        ),
        migrations.RemoveField(
            model_name='meslekib',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sosyalsecmeli',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sosyalsecmeli',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sosyalsecmeli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sosyalsecmeli',
            name='name',
        ),
        migrations.RemoveField(
            model_name='universitemeslekisecmeli',
            name='category',
        ),
        migrations.RemoveField(
            model_name='universitemeslekisecmeli',
            name='description',
        ),
        migrations.RemoveField(
            model_name='universitemeslekisecmeli',
            name='id',
        ),
        migrations.RemoveField(
            model_name='universitemeslekisecmeli',
            name='name',
        ),
        migrations.AddField(
            model_name='meslekia',
            name='degerlendirme_sistemi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='ders_adi',
            field=models.CharField(default='Tanımlanmamış', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='ders_kategorisi',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='ders_kitaplari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='ders_kodu',
            field=models.CharField(default='Tanımlanmamış', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='ders_ogrenim_ciktilari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='dersi_sunan_birim',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='dersin_amaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='dersin_dili',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='dersin_icerigi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='dersin_seviyesi',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekia',
            name='haftalik_konular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='on_kosullar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekia',
            name='yariyil',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='degerlendirme_sistemi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='ders_adi',
            field=models.CharField(default='Tanımlanmamış', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='ders_kategorisi',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='ders_kitaplari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='ders_kodu',
            field=models.CharField(default='Tanımlanmamış', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='ders_ogrenim_ciktilari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='dersi_sunan_birim',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='dersin_amaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='dersin_dili',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='dersin_icerigi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='dersin_seviyesi',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meslekib',
            name='haftalik_konular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='on_kosullar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meslekib',
            name='yariyil',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='degerlendirme_sistemi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='ders_adi',
            field=models.CharField(default='Tanımlanmamış', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='ders_kategorisi',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='ders_kitaplari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='ders_kodu',
            field=models.CharField(default='Tanımlanmamış', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='ders_ogrenim_ciktilari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='dersi_sunan_birim',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='dersin_amaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='dersin_dili',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='dersin_icerigi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='dersin_seviyesi',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='haftalik_konular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='on_kosullar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sosyalsecmeli',
            name='yariyil',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='degerlendirme_sistemi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='ders_adi',
            field=models.CharField(default='Tanımlanmamış', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='ders_kategorisi',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='ders_kitaplari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='ders_kodu',
            field=models.CharField(default='Tanımlanmamış', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='ders_ogrenim_ciktilari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='dersi_sunan_birim',
            field=models.CharField(default='Tanımlanmamış', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='dersin_amaci',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='dersin_dili',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='dersin_icerigi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='dersin_seviyesi',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='haftalik_konular',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='on_kosullar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universitemeslekisecmeli',
            name='yariyil',
            field=models.CharField(default='Tanımlanmamış', max_length=50),
            preserve_default=False,
        ),
    ]
