# Generated by Django 5.1.5 on 2025-02-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_remove_meslekia_category_remove_meslekia_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meslekia',
            name='dersin_amaci',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meslekia',
            name='dersin_icerigi',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meslekib',
            name='dersin_amaci',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meslekib',
            name='dersin_icerigi',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sosyalsecmeli',
            name='dersin_amaci',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sosyalsecmeli',
            name='dersin_icerigi',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitemeslekisecmeli',
            name='dersin_amaci',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universitemeslekisecmeli',
            name='dersin_icerigi',
            field=models.TextField(default='Tanımlanmamış'),
            preserve_default=False,
        ),
    ]
