# Generated by Django 5.1.5 on 2025-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=255)),
                ('ders_kodu', models.CharField(max_length=50, unique=True)),
                ('ders_kategorisi', models.CharField(max_length=255)),
            ],
        ),
    ]
